### PR TITLE
Cleaned Up Legacy Root Key Documentation

### LINKED ISSUE #609: I want documentation on how to create a root key extension
As an AaC plugin developer, I want documentation on how to create a root key extension, so that I can understand the how and why of extending the root keys.

## AC:
- [x] Ensure that legacy root key and root key extension documentation is updated to be legacy capability.
  - [x] Clarify that legacy root key and extension are in versions prior to v0.3.0, like with model inheritance.
  - [x] Modeling Data Structure Inheritance - Architecture-as-Code 0.3.4 documentation (arch-as-code.org)
- [x] Add a new section explaining the role of the new root key.
  - [x] Include how to use the new root key.
  - [x] Include example model reference of the new root key.
- [x] Make sure that example model references with the old root key and root key extensions reference the new root key. 
- [x] Make sure that definition references with the old root key and root key extensions reference the new root key.
  - [x] This should leverage the Sphinx include reference rather than the legacy copy/pastas.

### PR DESCRIPTION
**Pull request by lizzcondrey**
# Description
Clarified on legacy root key extension documentation when that implementation has stopped. Added reference to new root documentation. 

# Linked Items:
Closes #609 

### Added
- Reference to new root documentation. 

### Deprecated
- Legacy Root Key Extension capabilities. Clarified when the old implementation support ended and made reference to new implementation.

# Checklist:

- [x] I updated project documentation to reflect my changes.
- [ ] My changes generate no new warnings.
- [x] I updated new and existing unit tests to account for my changes.
- [x] I linked the associated item(s) to be closed.
- [x] I bumped the version.
- [x] I added the labels corresponding to my changes.

### CODE REVIEW

**Comment by lizzcondrey** [comment]
@cvchaparro corrected the merging for this branch so it is down to really only the pertinent files of the change.

**Review by cvchaparro — CHANGES_REQUESTED** [review]
The following files also require changes related to old root key references:
- `aac/docs/source/project_documentation/user_guide/user_library.md` (at least the "Defining, adding, and leveraging a Root Key" section)
- `aac/docs/source/project_documentation/user_guide/aac_language.md` (at least the "DSL Root Keys" section)

**Comment by lizzcondrey** [comment]
> The following files also require changes related to old root key references:
> 
> * `aac/docs/source/project_documentation/user_guide/user_library.md` (at least the "Defining, adding, and leveraging a Root Key" section)
> * `aac/docs/source/project_documentation/user_guide/aac_language.md` (at least the "DSL Root Keys" section)

Good catch, I had checked the Kill Root PR for which files had been updated for root key reference already and wasn't as thorough in confirming as I should have been. Getting them updated.

**Review by cvchaparro — COMMENTED** [review]
Looks like the changes from `user_library.md` were made but not the ones from `aac_language.md`.

**Review by cvchaparro — APPROVED** [review]

**Comment by lizzcondrey** [comment]
> ~Looks like the changes from `user_library.md` were made but not the ones from `aac_language.md`.~ Well, I feel sheepish. I didn't notice it was changed in the mainline.

It's all good because I was super confused at first because I could have sworn I had gotten that tweaked with the code snippet branch via a request you had made there, made me realize I had missed merging in main. lol

**Pull request merged**
